### ISSUE TITLE
Feat: Actual image search implementation

### ISSUE THREAD

**Issue by Sungtae124** [Sungtae124/SmartShutter#7]
## What is this issue? 🚀
실제 이미지 검색 구현을 위한 API 연결 및 기능 구현

## TODO 🏃‍♀️
- [ ] 구글 이미지 검색 API 연결
- [ ] 네이버 이미지 검색 API 연결
- [ ] 검색 결과 표시 관련 수정사항 확인 및 해결
